### ISSUE TITLE
XUnit / NUnit Integration

### ISSUE THREAD

**Issue by alkondrashov** [VIP-Logic/NBomber#33]
Example of proposed output message [XUnit]

> [xUnit.net 00:00:16.5057600]     Tests.My test [FAIL]
> Failed   Tests.My test
> Error Message:
> 
> Assertion #1 FAILED for Scenario Test HTTP (https://github.com) with 100 concurrent users
> Assertion #2 FAILED for Scenario Test HTTP (https://github.com) with 100 concurrent users
> Assertion #6 FAILED for Scenario Test HTTP (https://github.com) with 100 concurrent users
> Assertion #7 NOT FOUND for Test flow GET flow1
> Assertion #8 FAILED for Test Flow Test HTTP (https://github.com) with 100 concurrent users
> Assertion #9 FAILED for Step Test HTTP (https://github.com) with 100 concurrent users
> Assertion #10 FAILED for Step Test HTTP (https://github.com) with 100 concurrent users
> Assertion #11 FAILED for Step Test HTTP (https://github.com) with 100 concurrent users
> 
> Expected: True
> Actual:   False
> Stack Trace:
>    at Tests.My test() in /Users/alexkondrashov/Projects/NBomber/examples/NBomber.Examples.FSharp.Assertions/Tests.fs:line 93
> 
> Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
> Test Run Failed.
> Test execution time: 17.4991 Seconds

**Comment by AntyaDev** [comment]
nice!

**Comment by alkondrashov** [comment]
Example of NUnit output

```
Starting test execution, please wait...
Failed   Test1
Error Message:
 Assertion #1 FAILED for Scenario 'Test HTTP (https://github.com) with 100 concurrent users'
Assertion #2 FAILED for Scenario 'Test HTTP (https://github.com) with 100 concurrent users'
Assertion #6 FAILED for Scenario 'Test HTTP (https://github.com) with 100 concurrent users'
Assertion #7 NOT FOUND for Test Flow 'GET flow1'
Assertion #8 FAILED for Test Flow 'GET flow'
Assertion #9 FAILED for Step 'GET github.com/VIP-Logic/NBomber html'
Assertion #10 FAILED for Step 'GET github.com/VIP-Logic/NBomber html'
Assertion #11 FAILED for Step 'GET github.com/VIP-Logic/NBomber html'
Stack Trace:
   at NBomber.AssertionRunner.testFailed@51-1.Invoke(String msg) in /Users/alexkondrashov/Projects/NBomber/src/NBomber/Infra/AssertionRunner.fs:line 51
   at NBomber.AssertionRunner.test(AssertionResult assertionResult) in /Users/alexkondrashov/Projects/NBomber/src/NBomber/Infra/AssertionRunner.fs:line 59


Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 13.8205 Seconds
```

**Comment by alkondrashov** [comment]
suggestion for API for XUnit and NUnit:

buildScenario |> Scenario.assert' |> test

**Comment by alkondrashov** [comment]
Scenario.run
Scenario.runWithAssertions
