### ISSUE TITLE
With NBomber.Cluster, IStepContext StopCurrentTest and StopScenario does not stop testing occurring in other nodes

### ISSUE THREAD

**Issue by jimcomiskey** [VIP-Logic/NBomber#482]
If I start a test run running a scenario in a NBomber Cluster, and I call StopCurrentTest or StopScenario, that action only occurs locally.  It does not reach out to other nodes to stop the work.

**Comment by AntyaDev** [comment]
working on this now :)

**Comment by AntyaDev** [comment]
fixed in 4.0.0-beta11
