### ISSUE TITLE
Missing WithReportingSinks with C#

### ISSUE THREAD

**Issue by nullpainter** [VIP-Logic/NBomber#484]
I am upgrading NBomber from 2.1.2 to 3.2.2, and the `NBomberRunner.WithReportingSinks()` method has vanished, even though it's referred to in the F# code in the [InfluxDB sink](https://nbomber.com/docs/sinks-influxdb) documentation, and on the [General Concepts](https://nbomber.com/docs/general-concepts/) page.

I see there's a `NBomberContext.Reporting.Sinks` property, but this is read-only.

How should reporting sinks be added?

**Comment by AntyaDev** [comment]
Fixed
https://github.com/PragmaticFlow/NBomber/releases/tag/v3.3.0
