### ISSUE TITLE
HTTP client singleton is not allowed to be used across multiple scenarios

### ISSUE THREAD

**Issue by igoldin74** [VIP-Logic/NBomber#487]
Version: 3.3.0

Summary: using shared instance of HTTP factory is not allowed across multiple scenarios:
```
var step= Step.Create($"QueryStep",
                                    clientFactory: httpFactory,
                                    timeout: TimeSpan.FromSeconds(15),
                                    execute: async context =>
                                    { return; });
            var scenario1 = ScenarioBuilder.CreateScenario()               
            var scenario2 = ScenarioBuilder.CreateScenario()
            var scenario3 = ScenarioBuilder.CreateScenario()
            NBomberRunner.RegisterScenarios(new[] { scenario1, scenario2, scenario3 })
```
Above code would throw the following exception: 
_System.Exception : Client factories: 'http_factory' assigned to multiple scenarios. The client factory instance should be assigned to only one scenario.llowing exception:_

It used to allow that in prior version; Also, if it's a new requirement, how can we manage HTTP client(s) under such conditions?

**Comment by AntyaDev** [comment]
Hi @igoldin74 
Yes, it's a new validation that was added in the v3.3.0

You have several options:
- Create a HttpFactory instance with a unique name for each scenario.
```csharp
var factory1 = HttpFatory.Create("factory1")
var factory2 = HttpFatory.Create("factory2")
```
- Create a single HttpFactory and assign only one scenario. Then you can get access to HttpClient in scenario2 via IClientFactory.InitializedScenario
```csharp
factory1.InitializedScenario[0]
```
- You can create your HttpClient (without using HttpClientFactory) and use it directly inside any step.
You can check this [example](https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharpDev/HttpTests/SimpleHttpTest.cs#L15)
Also, you can use the extension method ToNBomberResponse to convert HttpMessageResponse to NBomber Response type.
[Here is example](https://github.com/PragmaticFlow/NBomber.Http/blob/dev/examples/CSharp/SimpleExample.cs#L22)

Sorry, this part is missing on the documentation page.
Very soon, I will improve the documentation and add more examples.

If it answers your question, could you please close this issue?

**Comment by igoldin74** [comment]
Thank you, the issue is resolved.
