### ISSUE TITLE
NotAllAgentsAvailable Exception Thrown With Many Agents

### ISSUE THREAD

**Issue by kweinberg1** [VIP-Logic/NBomber#489]
To appropriately test the systems under load, we have controllers with 45+ machines backing behind them.  

It is very common to run an NBomber test with 45 agents to fail because NBomber is unable to connect all to all of them.  The test doesn't often begin and developers are faced with an NotAllAgentsAvailable exception.

To reproduce this, we can create a basic NBomber test application with one scenario that does nothing.  Spawn many agent processes on multiple machines.  We will encounter this problem about 50% of the time with 45 agents and 100% of the time with 135 agents (3 agents per machine).

This makes scaling our tests to the target load nearly impossible.

**Comment by AntyaDev** [comment]
Hi @kweinberg1 

I started working on this.
I will keep you informed.

**Comment by AntyaDev** [comment]
Hi @kweinberg1 ,

I have fixed this issue in NBomber Cluster 4.0.0-beta3
