### ISSUE TITLE
Report file name contains invalid chars

### ISSUE THREAD

**Issue by KamilDuljas** [VIP-Logic/NBomber#490]
Hi, when i try set "WithReportFilename" as WithReportFileName("PerformanceTest" + DateTime.Now.ToString()) then throw exception:

![image](https://user-images.githubusercontent.com/87798948/194825683-6bd755ec-fcd2-4214-8bd4-83b9680f2f4e.png)

Moreover "WithReportFolder as the same name works fine:
WithReportFolder("PerformanceTest" + DateTime.Now.ToString())

**Comment by KamilDuljas** [comment]
hmmm after test I see that dirname syntax is also incorrect:

10:51:48 [ERR] Report.save failed
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. :
'C:\sources\repos\NBomberSample\NBomberSample\bin\Debug\ExSPerformanceTest_10\10\2022 10:50:42 AM'
  at void System.IO.FileSystem.CreateDirectory(string fullPath, byte[] securityDescriptor)
  at DirectoryInfo System.IO.Directory.CreateDirectory(string path)
  at ReportFile[[]] NBomber.DomainServices.Reports.Report.saveToFolder(ILogger logger, string folder, string fileName,
     FSharpList<ReportFormat> reportFormats, ReportsContent report)

**Comment by AntyaDev** [comment]
Hi @KamilDuljas 

I think it's because your file name contains invalid characters.
Try to filter them out.

It seems to me like it's not an NBomber bug.
I will close this issue.
