### ISSUE TITLE
Max WarmUpDuration is 60 seconds

### ISSUE THREAD

**Issue by KamilDuljas** [VIP-Logic/NBomber#491]
When I set WithWarmUpDuration above 60 seconds then it is ignore and warmup end after 60 seconds.
For example
 var HealthCheckScenario = ScenarioBuilder.CreateScenario("HealthCheck", steps: new[] { getExtHeatlhStep })
                .WithWarmUpDuration(TimeSpan.FromSeconds(120))
                .WithLoadSimulations(new[] {
                Simulation.InjectPerSec(30, TimeSpan.FromSeconds(60)),
                }
                    );

After 59 second, the counter jump up to 120 seconds and WarmUp was finished and Starting bombing

**Comment by AntyaDev** [comment]
Hi @KamilDuljas 

Looks like it's a bug.
Btw behavior do you expect in this situation?

I guess the warmup's duration time can't be bigger than the actual test.
Should NBomber throw a validation error in this case?

**Comment by KamilDuljas** [comment]
My typical usecase:
warmup set to 120 second,
bombing set  to 5 minutes.
When warmup's duration time is bigger than actual test, then NBomber should throw validation error with message.

Moreover i noticed that during warmup there are no send any request. Is it valid behavior?

**Comment by AntyaDev** [comment]
> When warmup's duration time is bigger than actual test, then NBomber should throw validation error with message

Agree. I will fix it.

> Moreover i noticed that during warmup there are no send any request. Is it valid behavior?

Not sure that I got it. Do you mean NBomber Scenario is not executing at all?

**Comment by AntyaDev** [comment]
@KamilDuljas 
Btw have you tried v4.0 beta?

**Comment by KamilDuljas** [comment]
> > When warmup's duration time is bigger than actual test, then NBomber should throw validation error with message
> 
> Agree. I will fix it.
> 
> > Moreover i noticed that during warmup there are no send any request. Is it valid behavior?
> 
> Not sure that I got it. Do you mean NBomber Scenario is not executing at all?

My mistake. Scenario has executed but I see only zeros in warm up stats. In my logs I see executed request but in stats not :)

**Comment by KamilDuljas** [comment]
> @KamilDuljas Btw have you tried v4.0 beta?

No. I'm going to do soon
