### ISSUE TITLE
Programmatically set NBomber Cluster ID

### ISSUE THREAD

**Issue by tomcain** [VIP-Logic/NBomber#495]
There is no obvious way to set the Cluster ID programmatically, it only appears to be settable via the cluster configuration files (coordinater-config.json and agent-config.json).

Being able to set this programmatically, dynamically deriving it from the environment, eliminates the need to hard-code in these files, which can be error prone when managing numerous test suites running across numerous clusters.

Additionally (or alternatively), it would be ideal to allow one to have finer grain control over the configuration so that it can be loaded from any standard IConfiguration source (e.g. environment variables, consul, etc).

**Comment by AntyaDev** [comment]
Hi @tomcain 
I will try to add this in v4

**Comment by AntyaDev** [comment]
The CLI argument "cluster-id" was added to NBomber v4.
Now you can use `--cluster-id=mycluster`

Also, the API method was added:
`NBomberClusterRunner.WithClusterId("mycluster")`
