### ISSUE TITLE
FeatureRequest: Break test and generate incomplete results

### ISSUE THREAD

**Issue by KamilDuljas** [VIP-Logic/NBomber#498]
When I want to break test, I send Ctrl+C in my console app, but the signal is not handled by nbomber and my app exit immidately.

I would like used some signal, for example ctrl+c and get info about break test and generate incomplete results.

**Comment by KamilDuljas** [comment]
Do you plan implement this feature or should I close the issue?

**Comment by AntyaDev** [comment]
Hi @KamilDuljas ,
Yes, this feature is on my list, but I am overloaded with other stuff.
I would appreciate it if someone would take it.

**Comment by AntyaDev** [comment]
Hi @KamilDuljas ,
It's done in NBomber v5
