### ISSUE TITLE
NBomber Cluster - data scoped to agent or agent group

### ISSUE THREAD

**Issue by tomcain** [VIP-Logic/NBomber#499]
NBomber has data feeds that are scoped to a specific scenario/step, but there is no such thing as a data feed that is scoped to an agent node in a cluster.

For example, I may need to create a large pool of data (e.g. users) before running tests, and store them in a DB. The coordinator would load the keys of the users, and evenly distribute and assign groups of keys to agents (or agent groups). When the agent process begins testing, the agent feed is used to retrieve the set of keys the agent should be working with.

If there is another existing way to accomplish this, please let me know.

**Comment by AntyaDev** [comment]
Hi @tomcain ,

It's a very good question. 
I also thought about this before, and I called this concept a cluster data partition.
Each agent on scenario init should receive a key range (say, from 0 to 100) or some other form of key space.

It's a very important feature for advanced use cases, and I will add it.

**Comment by AntyaDev** [comment]
NBomber adds support for automatic Scenario partition in the cluster.
The coordinator can understand how many of the same Scenarios will be executed in the cluster. Therefore, it assigns a sequential partition number to each Scenario and then distributes this information to the Agents.

For the developer, the contract looks like this:

```csharp
Scenario.Create()
    .WithInit(context => 
    {
        int currentPartition = context.ScenarioPartition.Number;
        int partionsCount   = context.ScenarioPartition.Count;
        return Task.CompletedTask; 
    })             
```

The contract is available by this [link](https://github.com/PragmaticFlow/NBomber.Contracts/commit/82be2eb44205f5c1003cdceeea5ebd1122384956)
