### ISSUE TITLE
Introduce option to let all steps in a started scenario iteration finish at the end of test run

### ISSUE THREAD

**Issue by tomwestin** [VIP-Logic/NBomber#503]
All  included steps in the scenario will then get the same step count. It could be made as an option in the NBomberRunner, JSON-configuration, or both.

**Comment by AntyaDev** [comment]
Hi @tomwestin ,
I guess this is resolved in NBomber v4.
https://www.nuget.org/packages/NBomber/4.0.0-beta4

Can you please try v4?

**Comment by tomwestin** [comment]
Hi @AntyaDev,

Okay, good. Sure, I'll try it.

**Comment by tomwestin** [comment]
Is this the default behavior now or do I need to configure it in some way?

**Comment by AntyaDev** [comment]
It should be a default behavior for v4
