### ISSUE TITLE
Periodic calls - help wanted

### ISSUE THREAD

**Issue by Cussa** [VIP-Logic/NBomber#504]
Hello,

I am preparing to do a load test, but I have a different requirement.

Each user does a sequence of initialisation calls, and after that starts to do some periodic calls every 10secs.

My idea is to check how many users the servers are able to handle. To do that, I should do all the initialisation calls and then start to do the periodic calls.

My idea was to prepare the initialisation on one step, and then on a new step, start some thread to handle the periodic calls.

But I don't know if, based on the tool architecture, this is the best plan.

Could you please advise?

Many thanks

**Comment by AntyaDev** [comment]
Hi @Cussa 

You can run preparation logic inside Scenario.WithInit()
And then use a regular Scenario + Steps

**Comment by AntyaDev** [comment]
Better to ask such questions in the Gitter channel

**Comment by Cussa** [comment]
Hi @AntyaDev 

I tried to take a look on the Gitter, but it seems so confusing that I decided to ask here again.

I tried to follow your idea of using the `WithInit` to do all the initialization. However, I need to do several requests here. Which leads me to the questions:
1. Is it possible to define a list of steps as the initizalition process? This means that I could reuse all the workflow from Steps to do the calls.
2. If the number 1 is not possible, how to do Http calls inside the `WithInit`? Trying to use the `Http.Send` causes an issue `The type arguments for method 'Task<Response> NBomber.Plugins.Http.CSharp.Http.Send<TFeedItem>(HttpRequest, IStepContext<HttpClient,TFeedItem>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

Just to clarify my usage:
- During the initialization, I have to do several calls to "prepare" the user. Consider that as the login/create the user.
- Then, I start a periodic call, with some intervals between then. My idea is to create the scenario with the step (that does the call) and pause.

Which leads me to more one question: I want to configure a number of users to be added per sec, but keep them running until the test finishes. Is it possible to do something like that?

I saw that the context in the `WithInit` does not have the client?

Is there any way that I can try to create something like that?

By the way: I tried to create a step that would be kept running forever until the tests finished, but this doesn't seem to work.

**Comment by AntyaDev** [comment]
Hi @Cussa 
Could you please look at NBomber v4 beta?
I think your case can be expressed now.
https://github.com/PragmaticFlow/NBomber/tree/dev/examples/CSharpProd/HTTP

> By the way: I tried to create a step that would be kept running forever until the tests finished, but this doesn't seem to work.

Can you please give me an example?

**Comment by Cussa** [comment]
Hello @AntyaDev 

I am on a vacation, and given that the tool was not able to reproduce our case, we did that manually. 

But I would be more than happy to try to recreate it using the NBomber as it gives us several reports.

But I will only be able to do that in around two weeks.

**Comment by AntyaDev** [comment]
Hi @Cussa ,
Sure, take your time.

> I want to configure a number of users to be added per sec, but keep them running until the test finishes

For this you should use: 
```csharp
Scenario.WithLoadSimulation(Simulation.RampingConstant(...), Simulation.KeepConstant(...))
```

> how to do Http calls inside the WithInit
https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharpProd/HTTP/SimpleHttpExample.cs#L15

**Comment by AntyaDev** [comment]
Hi @Cussa ,

Any updates?
Did you try NBomber v4?

**Comment by Cussa** [comment]
Hi @AntyaDev 

I took a quick look on that, as this we managed to do that with a custom tool crated by me.

Based on what I saw here, I still have some questions.

My use case is to have the following:
- imagine a "scenario", with several sub-sequential steps that are required to be done to initialise the user. This is what I was expecting to call in the "Init"
- after this init, I want to keep running the tests for a period of time. Inside this, I have some "steps" that are not running in sequence, but every X seconds it run. Each step has even a different timer configuration, which in some cases have some small random int added/subtract to the timer

Our idea was to reproduce in the most similar way the behaviour that our client will have.

Based on what I am seeing, it seems that the NBomber would still not able to do something like that. Can you confirm if my impressions are correct?

**Comment by AntyaDev** [comment]
It seems to me that this is possible to do with NBomber.
> imagine a "scenario", with several sub-sequential steps that are required to be done to initialise the user. This is what I was expecting to call in the "Init"

This is just scenario initialization. Scenario.WithInit()

> after this init, I want to keep running the tests for a period of time. Inside this, I have some "steps" that are not running in sequence, but every X seconds it run. Each step has even a different timer configuration, which in some cases have some small random int added/subtract to the timer

You can achieve any step order with NBomber.

```csharp
Scenario.Create("my scenario", context, () => 
{
    // shouldRunSpecialSteps: this function will tell me whether should I run "special steps" or not.
    var shouldExecute = shouldRunSpecialSteps(); 
    if (shouldExecute)
    {
        Step.Run("special step 1", ...);
        Step.Run("special step 2", ...);
    }

    Step.Run("regular step 1", ...);
    Step.Run("regular step 2", ...);
});
```

> Each step has even a different timer configuration, which in some cases have some small random int added/subtract to the timer

You can execute this logic inside **shouldRunSpecialSteps()**

**Comment by AntyaDev** [comment]
Hi @Cussa 
Does it help?

If yes, can you please close this issue?
