### ISSUE TITLE
Logger Configuration should support full override even for console 

### ISSUE THREAD

**Issue by AntyaDev** [VIP-Logic/NBomber#509]

**Comment by gowon** [comment]
I wanted to completely suppress the generation of the log file while running automated tests. Until this becomes exposed through the API, this snippet gets the job done:

```csharp
public static class NBomberContextExtensions
{
    public static NBomberContext WithoutInternalLogging(this NBomberContext context)
    {
        return context
            .WithLoggerConfig(() =>
                new LoggerConfiguration().Filter.ByIncludingOnly(_ => false));
    }
}
```

A lot of the console output gets mangled during the execution of scenarios, but I'm running this in scenarios where I don't want/need any legible console output.

**Comment by AntyaDev** [comment]
Hi @gowon 
Your approach is suitable for v3.
But in NBomber v4, you will not be able to pollute your console output with some irrelevant messages.
In v4, we changed the logger logic: 
Now you have separated two loggers:
- **Console Logger** - which is managed by NBomber and will not be available for customization. Plus, this logger will not print any of your messages in the console. It only prints messages that were sent by the NBomber host. 
- **Client Logger** - this logger is provided to be used by clients. The client can fully customize this logger. By default, this logger writes logs in the file, but it can be changed/customized.
