### ISSUE TITLE
Add option to forcibly halt all tests at end of simulation

### ISSUE THREAD

**Issue by mlschneid** [VIP-Logic/NBomber#521]
If I create a scenario with several load test simulations, I would expect that at the end of the very last simulation, all currently running tests are halted. This would give the ability to gauge how many tests were able to be completed within the given time, rather than how many tests were started within that time.

Could this functionality be added? 

```
  // All tests in progress should be stopped after two minutes
  var scenario1 = Scenario
      .Create("scenario_1", step1)
      .WithoutWarmUp()
      .WithLoadSimulations(
          Simulation.RampingConstant(copies: 100, during: TimeSpan.FromSeconds(60)),
          Simulation.KeepConstant(copies: 100, TimeSpan.FromSeconds(60))
      );
```

**Comment by AntyaDev** [comment]
Hi @mlschneid 

Yes, you are right and I am going to add such an option.

```csharp
NBomberRunner
            .RegisterScenarios(scenario)
            .EnableStopTestForcibly(true)
            .Run();
```
