### ISSUE TITLE
Add HTTP tracing for NBomber.Http

### ISSUE THREAD

**Issue by AntyaDev** [VIP-Logic/NBomber#528]
AC:
- [x] It should support granular tracing per HTTP call
- [x] It should write Debug log message
- [x] It should generate TraceId for request and response
- [x] It should be enabled via HttpClientArgs.Logger

```csharp
var scenario = Scenario.Create("http_scenario", async context =>
{
    var request =
        Http.CreateRequest("GET", "https://nbomber.com")
            .WithHeader("Accept", "application/json")
            .WithBody(new StringContent("{ some JSON }"));

    var clientArgs = HttpClientArgs.Create(logger: context.Logger);

    var response = await Http.Send(httpClient, clientArgs, request);

    return response;
});
```

**Comment by pentestguy** [comment]
Hey there!!

Is there any update on this? I saw the newer version which is 4.1.2

**Comment by AntyaDev** [comment]
Hi @pentestguy 

I am busy with other tasks and therefore can wait to take this one.
I hope it will be released with 4.2.

Btw, if you want to help with this, I will be able to assist. Just ping me in slack.

**Comment by pentestguy** [comment]
Hi @AntyaDev ,

Sure! Thank you..!!

**Comment by pentestguy** [comment]
Hey @AntyaDev , hope you are doing well.

Is this feature added in the latest release because I am unable to see the HTTP tracing logs?

Thank you

**Comment by AntyaDev** [comment]
Hi @pentestguy ,
Nice to see you :)

The priority for this task was changed due to migrating to NBomber Cluster. 
I will prioritize it for the next (5.3 or 5.4) version.
Also, NBomber.Http is open source, and I would like to see some contributions since this feature is not very complicated.

**Comment by leoashish** [comment]
Hey @AntyaDev ,
  I can work on this issue as suggested by you. Will go over the links provided. I will try my best to complete it.

**Comment by AntyaDev** [comment]
@leoashish Amazing!
Ping me if you need any help
This is the link on [NBomber.Http](https://github.com/PragmaticFlow/NBomber.Http)

**Comment by AntyaDev** [comment]
Hi @leoashish 
Do you have any progress?

**Comment by leoashish** [comment]
Hey @AntyaDev, I have done a rough coding.  We need to test it thoroughly.
One Question:
I have to log the Response to the Console for each HTTP Request. That's it no. According to the StackOverflow posts mentioned, that's what I understood. 
It will be completed in a few days.
Are there any Discord or slack channels where I can ask my queries?

**Comment by AntyaDev** [comment]
Hi @pentestguy 
let's use [NBomber dicussions](https://github.com/PragmaticFlow/NBomber/discussions)

**Comment by AntyaDev** [comment]
https://github.com/PragmaticFlow/NBomber.Http/commit/f5c54b5c8f12858038a704ea7471388b4795dbfa
