### ISSUE TITLE
Add user load distribution across the different scenarios

### ISSUE THREAD

**Issue by pentestguy** [VIP-Logic/NBomber#531]
Automated user load distribution based on a percentage per scenario.

Example - Let’s suppose we have 3 scenarios and we have 100 players then how can we distribute 30% of user load to scenario - 1 and 30% to scenario - 2 and 40% to the scenario.

**Comment by skinny** [comment]
+1 for this feature!

**Comment by AntyaDev** [comment]
https://nbomber.com/docs/nbomber/dynamic-workloads
