### ISSUE TITLE
Extend Http.Send() with HttpCompletionOption

### ISSUE THREAD

**Issue by Adelhaide22** [VIP-Logic/NBomber#536]
`HttpClient` in `System.Net.Http` has overload for method `Send()`, which accept `HttpCompletionOption` as parameter (it controls at what point operations on `HttpClient` should be considered completed and can improve performance).
Example usage:
`using var response = _httpClient.SendAsync(httpRequest, HttpCompletionOption.ResponseHeadersRead)`
I would like to have similar overload for NBomber's `Http.Send()` method.

**Comment by AntyaDev** [comment]
[NBomber.Http](https://github.com/PragmaticFlow/NBomber.Http/commit/8a647ef403758960f4356ac84eda82257596edc0)
[NBomber Example](https://github.com/PragmaticFlow/NBomber/commit/5fb5e6cf14f627f20ddabebf37e6393207ce082d)
