### ISSUE TITLE
Console stats throws exception and cancels the loading test

### ISSUE THREAD

**Issue by SandroMarques46** [VIP-Logic/NBomber#595]
Hello , I've been getting this exception **sometimes** when running loading tests using NBomber and unfortunately when it happens it cancels the test (reports folder only has the nbomber-log txt file). 

![Screenshot 2023-06-21 164713](https://github.com/PragmaticFlow/NBomber/assets/43933237/e6718f3c-a987-49c8-ba7b-ff093a604dbe)

- I don't mind not having a console during the test if it solves this issue, how can I disable it ? I don't see any option
- This time you can see it happened right when the test finished but I think it already happened in the middle of the test also.
- I'm not using Console.WriteLine, I'm not even using NBomber logger (context.Logger) , my code is not interfering at all with the console.

What can I try to debug this frustrating exception?

**Comment by AntyaDev** [comment]
hello,
what version of NBomber did you use?

**Comment by SandroMarques46** [comment]
> hello, what version of NBomber did you use?

Hello, sorry forgot to say, i'm using this C# packages : 

![image](https://github.com/PragmaticFlow/NBomber/assets/43933237/7f236160-fa2f-4ff5-8640-9fd3013c0dfa)

**Comment by AntyaDev** [comment]
Hi @SandroMarques46 ,

Do you have some Scenario.Init logic?
Can you please provide some examples I can use to reproduce it?

Also, in the next release NBomber v5.1.0 - NBomber will include local Realtime HTML report and Console Realtime functionality will be dropped. So I hope a new Realtime HTML report will replace the Console's "buggy" functionality in a few weeks.

**Comment by AntyaDev** [comment]
ping @SandroMarques46

**Comment by SandroMarques46** [comment]
Hi , i've been trying some tests on the past days and the error didn't appear. Hard to replicate :( . You can close this issue for now and I'll give updates if it happens again with more data to show proof of it , thanks

**Comment by AntyaDev** [comment]
Hi @SandroMarques46 ,
please try NBomber v5.1.0 - should be fixed
