### ISSUE TITLE
Am I doing load testing correctly ?

### ISSUE THREAD

**Issue by jayonsoftware** [VIP-Logic/NBomber#597]
If I want to find out what are the maximum connections my server can support. Is the following the correct way of doing it?

**.WithLoadSimulations(Simulation.Inject(rate: 100, interval: TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(30))**

And I keep increasing the rate until it fails?

Also, I noticed that. 

**.WithReportingInterval(TimeSpan.FromSeconds(5))**

It does not update the report every 5 seconds; the report is only getting updated once the whole testing is don't

Maybe these issues are happening since I am using LinqPad ?

```
var goodRequest = 0;
var badRequest = 0;
var httpClient = new HttpClient();

var scenario = Scenario.Create("SpeedTest", async context =>
{
	var request = Http.CreateRequest("GET", "https://localhost:5001/").WithHeader("Accept", "application/json");

	var response = await Http.Send(httpClient, request);
	
	if(response.StatusCode == "OK") {
		goodRequest++;
	} else {
		badRequest++;
		response.StatusCode.Dump();
		Response.Fail();
	}
	return Response.Ok();

})
	.WithoutWarmUp()
	//.WithLoadSimulations(Simulation.KeepConstant(copies: 1, during: TimeSpan.FromSeconds(20))
	.WithLoadSimulations(Simulation.Inject(rate: 100, interval: TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(30))
);


var nBomber = NBomberRunner.RegisterScenarios(scenario)
.WithWorkerPlugins(new HttpMetricsPlugin(new [] { HttpVersion.Version1, HttpVersion.Version2 }))
.WithReportingInterval(TimeSpan.FromSeconds(5))
.WithReportFileName("Report")
.WithReportFolder(@"C:\Data\NBomberData");

nBomber.Dump();

nBomber.Run();
```

**Comment by AntyaDev** [comment]
Hi @jayonsoftware 

why do you need this counter?
```var goodRequest = 0;```

**Comment by jayonsoftware** [comment]
I do not think I need that, I was trying to keep a count of how many requests were good and how many were bad, but now I see that on your reports, you have that. 

What I am trying to do is benchmark new hardware to see how many concurrent good requests I can make before it starts failing. The part I don't understand dis 

`.WithLoadSimulations(Simulation.Inject(rate: 100, interval: TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(30))`

Am I saying to run 100 concurrent threads in 30 seconds? What is the best way to find a number so I can say "We can do a maximum of ### requests in a min"

Thanks

Jay

**Comment by AntyaDev** [comment]
> Am I saying to run 100 concurrent threads in 30 seconds?

Yes

> What is the best way to find a number

You can combine a few load simulations:
```
Simulation.RampingInject(rate: 200, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(1)),
Simulation.Inject(rate: 200, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(1)) 
```

You can read more [here](https://nbomber.com/docs/using-nbomber/basic-api/load-simulation)

Also, pay attention on physical latency between your NBomber and target host. You can measure it by using [PingPlugin](https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharpProd/HTTP/SimpleHttpExample.cs#L31),
