### ISSUE TITLE
Incorrect construction of html-reports

### ISSUE THREAD

**Issue by ghost** [VIP-Logic/NBomber#605]
Hello,
I have a problem, my reports don't show graphs with latency and load.
The problem was in calling the toLocaleString method without passing a parameter in the report itself:
`var date = new Date(viewModel.FinalStats.TestInfo.Created);
 viewModel.FinalStats.TestInfo.Created = date.toLocaleString();`
![1](https://github.com/PragmaticFlow/NBomber/assets/103137287/f3980567-145d-48f3-9833-58e800b58e47)

If you pass the value 'en-US', then everything works correctly, and the graphs are displayed again
`var date = new Date(viewModel.FinalStats.TestInfo.Created);
 viewModel.FinalStats.TestInfo.Created = date.toLocaleString('en-US');`
![image](https://github.com/PragmaticFlow/NBomber/assets/103137287/c76760e7-c076-4677-ab7d-4cc05e619531)

I have a different date format on my computer

**Comment by AntyaDev** [comment]
Hi @Ilyichovskiy ,
And thank you for informing me about this issue.
I will try to fix it soon.

**Comment by AntyaDev** [comment]
Hi @Ilyichovskiy ,
Can you please try the latest beta version - 5.1.2-beta.0
If it helps, then I will publish a patch

**Comment by AntyaDev** [comment]
ping @Ilyichovskiy

**Comment by ghost** [comment]
> ping @Ilyichovskiy

?

**Comment by AntyaDev** [comment]
@Ilyichovskiy did you try the latest beta with the fix?

**Comment by ghost** [comment]
@AntyaDev it works, thank you

**Comment by routaz** [comment]
I am using the 5.6.0-beta.0 package and have same problem with Date showing up as invalid and no charts displayed.

<img width="1382" alt="Screenshot 2024-03-04 at 15 07 33" src="https://github.com/PragmaticFlow/NBomber/assets/68007175/9748a8c6-749d-4a10-b1ec-7458b546d5a8">

**Comment by AntyaDev** [comment]
Hi @routaz ,
Can you please attach your report?

**Comment by routaz** [comment]
Sure. Here's all of them :)
[nbomber_report_2024-03-04--13-05-10.csv](https://github.com/PragmaticFlow/NBomber/files/14492191/nbomber_report_2024-03-04--13-05-10.csv)
[nbomber_report_2024-03-04--13-05-10.md](https://github.com/PragmaticFlow/NBomber/files/14492192/nbomber_report_2024-03-04--13-05-10.md)
[nbomber_report_2024-03-04--13-05-10.txt](https://github.com/PragmaticFlow/NBomber/files/14492193/nbomber_report_2024-03-04--13-05-10.txt)

Can't attach the .html file.

**Comment by routaz** [comment]
@AntyaDev Are those reports enough?

**Comment by AntyaDev** [comment]
Hi @routaz ,
Yes, looks enough.
Thanks!

**Comment by AntyaDev** [comment]
@routaz I need also HTML report.

**Comment by routaz** [comment]
@AntyaDev Okay, can't add it as .html file, so here's all the files as .zip. Hopefully this is alright.
[Reports_NBomber.zip](https://github.com/PragmaticFlow/NBomber/files/14559543/Reports_NBomber.zip)

**Comment by AntyaDev** [comment]
Thanks @routaz ,
I think we can reproduce the issue now.
We will take this for the current version.

**Comment by AntyaDev** [comment]
Hi @routaz 
Could you please try [NBomber 5.6.0-beta.5](https://www.nuget.org/packages/NBomber/5.6.0-beta.5)

**Comment by routaz** [comment]
Alright, will try that and let you know!

**Comment by routaz** [comment]
Hi @AntyaDev
Now "Created" date is populating as it should, but charts are still empty. How is the chart creation handled?

**Comment by AntyaDev** [comment]
Hi @routaz 
Could you please attach your HTML report.
Basically, there is an issue in correct parsing Created datatime since it plays important role for drawing charts. For some reason your CreatedDate uses special format that parsed incorrectly.

**Comment by routaz** [comment]
@AntyaDev Thank you for looking into this :)
[Archive.zip](https://github.com/PragmaticFlow/NBomber/files/14650102/Archive.zip)

**Comment by AntyaDev** [comment]
@routaz 
Please try https://www.nuget.org/packages/NBomber/5.6.0-beta.6

**Comment by routaz** [comment]
@AntyaDev Unfortunately still no luck :(
But this is not a HUGE issue, as I am setting up real-time monitoring. But a little annoyance still.

**Comment by AntyaDev** [comment]
@routaz please attach your HTML report; we need to fix it :)

**Comment by routaz** [comment]
@AntyaDev 
Hi, here's another batch of reports :)
[Archive.zip](https://github.com/PragmaticFlow/NBomber/files/14754533/Archive.zip)

**Comment by AntyaDev** [comment]
@routaz I opened the HTML from your report and it renders ok.
![image](https://github.com/PragmaticFlow/NBomber/assets/1080518/aa5fb68e-35e4-43f6-8dd3-9b37cd0aca2d)

**Comment by AntyaDev** [comment]
@routaz can you please check this line of code in Debug.
What values you get? I mean **date** variable
![image](https://github.com/PragmaticFlow/NBomber/assets/1080518/9eecf4e5-1dc5-46bf-9c9e-105beb7af158)

**Comment by routaz** [comment]
@AntyaDev 

Oh, this is interesting!
I opened the same file without render.
<img width="1304" alt="Screenshot 2024-03-27 at 11 08 48" src="https://github.com/PragmaticFlow/NBomber/assets/68007175/08f6fb3b-e912-4f4c-9982-62538a1b3ad1">

You mean just debug from Nbomber the TestInfo.Created?
(or from where do I find that line of code?)

Won't have time to work on this today, but will get back to you as soon as possible :)

**Comment by AntyaDev** [comment]
@routaz You can find this line of code in the HTML report. You have something with your locale settings that prevents you from parsing DateTime.

**Comment by AntyaDev** [comment]
@routaz please check https://www.nuget.org/packages/NBomber/5.6.0-beta.7
I have set Invariant Culture, maybe it will help.

**Comment by AntyaDev** [comment]
@routaz any updates?

**Comment by routaz** [comment]
@AntyaDev Sorry, I am offline for few days now. But will get back to you as soon as possible regarding this :)

**Comment by AntyaDev** [comment]
@routaz, we are about to release a new version, and I would like to make sure that our fixes work.
Could you please tell me what locale you currently have on your PC? I would like to set your locale and verify it.
Is it `fi_FI` ?

**Comment by routaz** [comment]
@AntyaDev Yes, I'm located in Finland and using macOS Sonoma 14.3.1 if that makes any difference. I get access to my PC on day after tomorrow most likely and will test it then!

**Comment by AntyaDev** [comment]
Hi @routaz 
Will you be able to check today?
Thank you so much for your attention and participation.

**Comment by routaz** [comment]
@AntyaDev Finally got online briefly!
Still no luck with reports, here's the archived reports, included screenshot of the packages I am using as well.
Can you confirm if it works on your end. I'll try to debug on the date value from report too.
[Archive.zip](https://github.com/PragmaticFlow/NBomber/files/14833696/Archive.zip)

EDIT:
Here's a screenshot of date value:
<img width="543" alt="Screenshot 2024-04-02 at 10 55 01" src="https://github.com/PragmaticFlow/NBomber/assets/68007175/0450bfa2-b58c-43bc-9162-9c40afee207e">

**Comment by AntyaDev** [comment]
@routaz can you please install **en-US** locale on your laptop.
it seems it fails to format datetime to en-US locale

**Comment by AntyaDev** [comment]
@routaz I have changed the parsing library for date time in HTML report. 
Could you please try new [version: 5.6.0-beta.9](https://www.nuget.org/packages/NBomber/5.6.0-beta.9)

**Comment by routaz** [comment]
Hi @AntyaDev
Just tried with en_US locale and latest package. Still no graphs. I really start to think this is something on my end and with laptop settings. I'll add zip with test reports, screenshots of my settings and let me know if you need debug-logs from Rider.
And if you want to contact me directly via email, you can write to me to routaz@gmail.com
[Archive.zip](https://github.com/PragmaticFlow/NBomber/files/14869612/Archive.zip)

**Comment by AntyaDev** [comment]
@routaz, Can you please debug this function? What does it return?

![image](https://github.com/PragmaticFlow/NBomber/assets/1080518/97c2f5e6-4f91-4245-adc1-51e9acebdd2f)

**Comment by AntyaDev** [comment]
fixed
