### ISSUE TITLE
SingalR support ?

### ISSUE THREAD

**Issue by KANekT** [VIP-Logic/NBomber#612]
is it possible to test SingalR ?

**Comment by MihaelPavlov** [comment]
@KANekT 
I see no reason why it can't be tested.

For example, if you have an endpoint that sends a message.
You create a step, set it up inside, and make a call to the endpoint.
And then you can create different scenarios with NBomber

Information that might help you -> https://stackoverflow.com/questions/61275705/how-do-you-test-a-signalr-application-load-functional-combined-hosted-on-an

**Comment by AntyaDev** [comment]
@KANekT 
Yes. 
You should create and use a SignalR client inside your Scenario/Step.
I would recommend to look at MQTT (Pub/Sub via WebSockets) load tests. 

- [Ping Pong](https://github.com/PragmaticFlow/NBomber/tree/dev/examples/Demo/MQTT)
- [Pub Sub](https://github.com/PragmaticFlow/NBomber/tree/dev/examples/Demo/Features/ClientPool)
