### ISSUE TITLE
Scenario Timeout

### ISSUE THREAD

**Issue by lauji2k19** [VIP-Logic/NBomber#613]
### Discussed in https://github.com/PragmaticFlow/NBomber/discussions/611

<div type='discussions-op-text'>

<sup>Originally posted by **lauji2k19** August 11, 2023</sup>
Hi,

I am using NBomber V4.1.2 and facing an issue where the scenario is stopped before all steps are able to complete. I figure this is because the load test has several sequential requests and exceeds the scenario duration. We first make a sequence of 4 HTTP requests which take anywhere between 1-10 seconds each to respond. Then, the fifth step is asynchronous so we ping an endpoint every second for 2 minutes maximum. Here's a rough time estimate for each step:

1. ~1 sec. 45/45 requests executed.
2. ~1-4 secs. 45/45 requests executed (1 failed, which is OK so I expect the total to now be 44).
3. ~4-10 secs. 26/44 requests executed.
4. ~4-6 secs. 21/44 requests executed.
5. ~15-30 secs. 0/44 requests executed.

The test is run with the load simulation:
`Simulation.Inject(rate: 3, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromSeconds(15)`

The goal of the test is to send 3 RPS for 15 seconds (and later on with higher loads) and see how long it takes for the system to complete the whole process and identify any bottlenecks, but I can't do this since the scenario ends before all steps execute. Is there a way to configure the test to only stop either if all iterations complete, or at a max cutoff, say, 10 minutes?</div>

**Comment by AntyaDev** [comment]
Hi @lauji2k19 ,

The default behavior of NBomber is that **it waits up to 1 min** on all scenarios to finish.
I think I could add the configuration to extend such duration.

For now, there is no such configuration that you described.

**Comment by AntyaDev** [comment]
@lauji2k19 

I just checked it seems there is some bug and it waits less than 1 min.
But for sure there is no configuration to change it.

**Comment by AntyaDev** [comment]
Hi @lauji2k19 

We are almost done with this issue. 
This issue will be fixed in v5.2.1
I hope till following Monday the package with a fix will be published.

**Comment by AntyaDev** [comment]
Hi @lauji2k19 ,
Please try this version: https://www.nuget.org/packages/NBomber/5.2.1-beta.1

Here you can find the description: https://github.com/PragmaticFlow/NBomber/issues/618
