### ISSUE TITLE
HttpClient in multi-thread mode

### ISSUE THREAD

**Issue by avoitenko** [VIP-Logic/NBomber#616]
Hello. @AntyaDev 
When I am using HttpClient in multithread testing.
It does not lead to a performance increase.
I think it refers to locks?
Do you have an optimized version of HttpClient in your framework?
Please clarify. Thanks.

**Comment by AntyaDev** [comment]
[NBomber.Http](https://nbomber.com/docs/protocols/http) is using standard HttpClient with no locks.
Can you please elaborate more about your test case? You can paste some code here.

**Comment by avoitenko** [comment]
my python test server
`
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
import time
sleepMsc = lambda x: time.sleep(x/1000.0)

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        #sleepMsc(1)
        self.send_response(200)
        self.end_headers()

PORT = 9090

def run():
    print("start server on port %d" % PORT)
    server = ThreadingHTTPServer(('0.0.0.0', PORT), Handler)
    server.serve_forever()

if __name__ == '__main__':
    run()
`

**Comment by avoitenko** [comment]
my NBomber test
`
public class NewTest
{
    public void Run()
    {
        string url = "http://127.0.0.1:9090";
        HttpClient client = new();
        //---
        var scenario = Scenario.Create("scenario1", async context =>
            {
                //---
                var request = Http.CreateRequest("GET", url);
                var response = await Http.Send(client, request);
                //---
                if (response.IsError)
                    return Response.Fail();
                
                //---
                context.Logger.Information("Result: OK,  thread:{0}, iteration: {1}",
                                            context.ScenarioInfo.ThreadNumber,
                                            context.InvocationNumber);
                return Response.Ok();
            })
            .WithoutWarmUp()
            .WithLoadSimulations(
                Simulation.KeepConstant(1, TimeSpan.FromSeconds(10))
            );

        //---
        NBomberRunner
            .RegisterScenarios(scenario)
            .WithReportFileName("report")
            .WithReportFolder("reports")
            .WithReportFormats(ReportFormat.Txt, ReportFormat.Html, ReportFormat.Md)
            .WithReportingInterval(TimeSpan.FromSeconds(10))
            .Run();
    }
}
`

**Comment by avoitenko** [comment]
I compare the results with JMeter:
Threads :                      |    1       |      2     |       3     |    4      | 
Iterations JMeter:         | 16000  | 25000  | 31000   |32000  | using 4th -> number of iterations + 100 %
Iterations NBomber:     | 7000   | 9000    | 10000   |10000  | using 4th -> number of iterations + 42 %
So I am expecting the same rate as in JMeter.
I think that HttpClient is not optimized or has settings by default that prevent doubling the result.

**Comment by AntyaDev** [comment]
Hi @avoitenko ,
Why do you use KeepConstant instead of [Inject ](https://nbomber.com/docs/nbomber/load-simulation#inject)?

Also, you don't need to check if (response.IsError) - 
By default, when a Step returns a failed Response or an unhandled exception is thrown, NBomber will automatically mark the whole iteration as failed and restart it.
 - you can use https://nbomber.com/docs/nbomber/scenario#scenario-restartiterationonfail

**Comment by avoitenko** [comment]
@AntyaDev 
This is my multi-thread performance investigation.
[https://github.com/avoitenko/NBomber.FastHttpClient](https://github.com/avoitenko/NBomber.FastHttpClient)

**Comment by AntyaDev** [comment]
@avoitenko 
Why do you use KeepConstant?

Can you please re-run your tests with Inject instead of KeepConstant?
And please don't use logs for such tests if you want to get higher RPC than JMeter.

**Comment by avoitenko** [comment]
> @avoitenko Why do you use KeepConstant?

@AntyaDev 
I am not using it for two reasons:
1. I don't like to limit the number of iterations by time. I need as much speed as possible.
2. Inject mode works incorrectly with **ThreadNumber** for me. I am using this variable for my logic.

For example:
`Simulation.Inject(rate: 50, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromSeconds(2))`

I am expecting that 50 threads invoke two times 
but in fact:
iteration 1 invokes 74 times, max value of ThreadNumber is 74.
iteration 2 invokes 25 times, max value of ThreadNumber is 45.
`await Task.Delay(x_msec)`
the delay of execution as in your example affects it and destroys my logic.

KeepConstant is more convenient for me, because
no problems with ThreadNumber
no problem with the performance

**Comment by AntyaDev** [comment]
> I am expecting that 50 threads will invoke two times
NBomber uses Tasks (Promises in Js) - a cheaper abstraction than thread.

The problem with KeepConstant is that - the target system blocks your execution, and you receive unrealistic latency and RPS. It's a good candidate for WebSockets.
On production workload, your system will give you different numbers.

**Comment by AntyaDev** [comment]
Please read this: https://nbomber.com/docs/protocols/http/#load-simulation

**Comment by AntyaDev** [comment]
Also, try to run two similar scenarios with Inject on NBomber and alternative configuration on Jemeter.
I do understand that you want to work with iterations (that currently is not supported), but I would like to see a fair comparison in terms of performance btw NBomber and jMeter.

**Comment by avoitenko** [comment]
@AntyaDev 
Thanks for your advice. I will test **Inject** mode and back with the test results.
