### ISSUE TITLE
Add Scenario Completion Timeout

### ISSUE THREAD

**Issue by AntyaDev** [VIP-Logic/NBomber#618]
This feature is based on the issue: https://github.com/PragmaticFlow/NBomber/issues/613

When NBomber finishes load tests, it waits for all running scenarios to complete their tasks.

```csharp
NBomberRunner
    .RegisterScenarios(scenario)
    .WithScenarioCompletionTimeout(TimeSpan.FromMinutes(5))
    .Run();
```
You can set it via JSON config
```json
{
    "GlobalSettings": {
        "ScenarioCompletionTimeout": "00:05:00"
    }
}
```

**Comment by destructorvad** [comment]
Hello @AntyaDev .
Are there any way to get information from statistics result about unfinished scenarios ?

**Comment by AntyaDev** [comment]
I think not.
But If it's needed for your organization we can provide such info.

**Comment by destructorvad** [comment]
thanks, I will keep it in mind
