### ISSUE TITLE
missing doc - setting license in teamcity

### ISSUE THREAD

**Issue by pavdro-ttl** [VIP-Logic/NBomber#631]
Hey,
I'm not entirely sure how to set a license when I run tests in TeamCity, nothing in documentation either, please advice?

Thanks,
Pav

**Comment by AntyaDev** [comment]
Hi @pavdro-ttl ,

Can you use [CLI args](https://nbomber.com/docs/getting-started/cli)?

for example:
```
MyLoadTest.dll --license=YOUR_LICENSE_KEY
```

**Comment by pavdro-ttl** [comment]
> Hi @pavdro-ttl ,
> 
> Can you use [CLI args](https://nbomber.com/docs/getting-started/cli)?
> 
> for example:
> 
> ```
> MyLoadTest.dll --license=YOUR_LICENSE_KEY
> ```

we are using dotnet test 🤷 I don't imagine it passes that param through.

**Comment by AntyaDev** [comment]
what about Environment.GetEnvironmentVariable("YOUR_LICENSE_KEY")
?

**Comment by pavdro-ttl** [comment]
> what about Environment.GetEnvironmentVariable("YOUR_LICENSE_KEY") ?

ok, I did that and can see it come through! but still getting the warning message

> [WRN] THIS VERSION IS FREE ONLY FOR PERSONAL USE. You can't use it for an
 organization.

But back to my original point - can we have these notes in the official docs?

**Comment by AntyaDev** [comment]
> ok, I did that and can see it come through! but still getting the warning message

You can then pass it into NBomberRunner something like this:
```NBomberRunner.Run("--license", "YOUR_LICENSE_KEY")```
or 
```NBomberRunner.WithLicense("YOUR_LICENSE_KEY")```

> But back to my original point - can we have these notes in the official docs?

Sure, we will update the doc about the license.

**Comment by pavdro-ttl** [comment]
> > ok, I did that and can see it come through! but still getting the warning message
> 
> You can then pass it into NBomberRunner something like this: `NBomberRunner.Run("--license", "YOUR_LICENSE_KEY")` or `NBomberRunner.WithLicense("YOUR_LICENSE_KEY")`

yes, here's what I have! so maybe its ok, but warning message is wrong?

```
  var runner = NBomberRunner
      .RegisterScenarios(scenario);

  if (!string.IsNullOrWhiteSpace(_nBomberLicenseKey))
  {
      runner.WithLicense(_nBomberLicenseKey);
  }

  var result = runner.Run();

```

**Comment by AntyaDev** [comment]
You shouldn't see any Warning message related to the license. 

You can try to run your NBomber as a regular Console App (without dotnet test) and see what it prints about the license.
