### ISSUE TITLE
HTML report issue with displaying step latency

### ISSUE THREAD

**Issue by AntyaDev** [VIP-Logic/NBomber#633]
For some reason, Step's latency chart is inconsistent compared to Scenario. And sometimes, RPS can grow further than specified in LoadSimulations.Inject

**Comment by leoashish** [comment]
Hey @AntyaDev, I am new here, going through this project's code structure and trying to understand how it works. I would love to work on this issue/bug.

**Comment by AntyaDev** [comment]
Hi @leoashish 
This task requires a deep knowledge of the core engine and I would suggest starting from something simpler.
For example: 
- [Add HTTP tracing](https://github.com/PragmaticFlow/NBomber/issues/528)

**Comment by leoashish** [comment]
Yeah, I can take that up. Thanks for suggesting. Let me see the issue and understand the implementation.

**Comment by AntyaDev** [comment]
Step RPS is slightly different because it starts with a random startup delay to simulate a more real workload. 

```fsharp
do! Task.Delay startDelay
```
