### ISSUE TITLE
Testing Nomber fom UI like jMeter

### ISSUE THREAD

**Issue by amitdixit** [VIP-Logic/NBomber#635]
I am making an blazor UI application like jmeter with nbomber , every thing works well the only problem is I am not able to get the console message. I think NBomber is printing message with Console.WriteLine and not with Logger. Hence I am not able to capture those messages and push it to the client with SignalR.

I got some level of success when I attached the Process and displayed the message in UI.

Does NBomber has any UI application which testers can directly use, since at present it takes my time where I have to write all the steps and scenarios and then hand it over to the testing team for the load test.

**Comment by AntyaDev** [comment]
Hi @amitdixit 
NBomber uses [SpectreConsole](https://github.com/PragmaticFlow/Serilog.Sinks.SpectreConsole) for logging into Console

```fsharp
let config = LoggerConfiguration()
config.WriteTo.SpectreConsole(outputTemplate, minLevel = LogEventLevel.Verbose) |> ignore
config.CreateLogger()
```

Also, I think [this doc](https://nbomber.com/docs/nbomber/logger) can be useful

**Comment by AntyaDev** [comment]
@amitdixit can you please elaborate a bit more about your UI tool?
What is the purpose for this, etc?

**Comment by amitdixit** [comment]
Hi @AntyaDev ,
Thanks for the reply, its not only about logging , I want to get all the messages which are being rendered in stdout/console as I want to display those message on an UI. Blazor/SPA apps.

So here is what I am intending to do. 
1. A Generic Library which will refer NBomber for the load testing.
2. The Web App will have the UI from which we'll accept all the data like Method,URL, iteration, duration etc... which are needed for the load test.
3. While this works, I don't find any direct way by which I can show all the NBomber data which is being displayed on the stdio on the browser screen.

**Comment by amitdixit** [comment]
> @amitdixit can you please elaborate a bit more about your UI tool? What is the purpose for this, etc?

So as a Dev we can write our Test and scenarios but what about those testers who are not versed with C#/F# and who have being using tools like jMeter, basically I want to implement a very basic variant which is similar to jMeter

**Comment by AntyaDev** [comment]
@amitdixit I got you. I must admit that your idea to build a tool similar to jMeter UI looks excellent!
Did you try to intercept log events/messages by adding your own Serilog Sink?

**Comment by amitdixit** [comment]
Yes I did get the logs but not the actual statement which the NBomber is rendering like all the usual NBomber statement.


What I did to make it work was this. I created a console application which uses NBomber as the library. That console app takes all the necessary data like url , method etc as the argument then in another web app I added the console application as a Process and then rendered it on the UI using exterm js library. But I lost all the formatting and since I am not a UI developer I didn't give much to it.

**Comment by AntyaDev** [comment]
Do you have an example regarding Serilog Sink?

What do you mean by "all the usual NBomber statement" - is it a stats table?

**Comment by amitdixit** [comment]
Yes stats. Will share a repo by this weekend .

Was thinking to use Serilog signalR. Or any mechanism to capture the message via signalR.  Or any other mechanism in case I use windows forms etc...

**Comment by AntyaDev** [comment]
Ah, now it's clear. The Console Statistics Table that NBomber renders is drawn via Spectre.Console and not by Serilog. That's the reason why you can get it via Serilog Sink.

Some time ago, I started working on a prototype that allows to query NBomber via HTTP API. Basically it's a local HTTP server hosted inside NBomber. I think that is what you need :) Such functionality will allow you to work with NBomber even remotely.

Does it make sense?

**Comment by AntyaDev** [comment]
Hi @amitdixit 
Do you think it makes sense to provide some HTTP API to allow you to query NBomber and fetch stats?

**Comment by amitdixit** [comment]
Should be to a good option to start with. I mean why such a great tool doesn't have any UI for testing is very surprising. Since not everyone is a developer. 

But thanks for taking an interest here.

I wanted to create a bundled app just like a jmeter using NBomber with an UI

**Comment by AntyaDev** [comment]
Hi @amitdixit 
Some time ago, I have added this task to the backlog: https://github.com/PragmaticFlow/NBomber/issues/593
Will you be able to share your tool with the community?

**Comment by amitdixit** [comment]
Sure it's very basic nothing fancy just a web app calling the console application and the out from stdout is reflected on UI on exterm Library. I will share surely if that helps
