### ISSUE TITLE
Intermittent repeated test step names in html report

### ISSUE THREAD

**Issue by ctissellb** [VIP-Logic/NBomber#647]
We are frequently seeing an issue with report generation in NBomber 5.4.1 in which test step names are repeated in the Scenarios->Charts tab of the html report.  This *only* seems to occur on the charts tab. The test step names in the rest of the report seem to be correct. The graph data also seems to be correct. It is only the test step names that are repeated.

This seems to happen on a different test step each time. Report generation will get the first few names correct and then get stuck on one and repeat if for the rest of the report.

![Capture](https://github.com/PragmaticFlow/NBomber/assets/156009638/7ddc5350-d650-4c23-8538-aa516c64932a)

**Comment by AntyaDev** [comment]
Seems it's similar case
https://github.com/PragmaticFlow/NBomber/issues/664

**Comment by ctissellb** [comment]
Awesome. I'll keep an eye on it, thanks.

**Comment by AntyaDev** [comment]
Hi @ctissellb, @andreycha
Could you please attach your HTML reports that include this bug here?

**Comment by andreycha** [comment]
Hi @AntyaDev ,
Here you go: [nbomber_report_2024-02-14--14-56-25.zip](https://github.com/PragmaticFlow/NBomber/files/14328678/nbomber_report_2024-02-14--14-56-25.zip)

**Comment by AntyaDev** [comment]
Hi @ctissellb , @andreycha 
It seems I have found the issue in Js code :)
I added fix for [NBomber 5.6.0-beta.2](https://www.nuget.org/packages/NBomber/5.6.0-beta.2)
Could you please try it and give me feedback?

**Comment by andreycha** [comment]
Hi @AntyaDev ,
Updated to the suggested version, ran the test several times, the issue seems to be gone.
