### ISSUE TITLE
[Question] Which load simulation does warmup use?

### ISSUE THREAD

**Issue by andreycha** [VIP-Logic/NBomber#654]
Hi,

There is something regarding warmup I couldn't find in the documentation. Assuming I have following configuration:

```cs
.WithWarmupDuration(TimeSpan.FromMinutes(1))
.WithLoadSimulations(
    Simulation.RampingInject(20, TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(30)),
    Simulation.Inject(20, TimeSpan.FromSeconds(1), TimeSpan.FromMinutes(1)))
```

What kind of load will be produced during warmup phase? I assume it will ramp up to 20r/s within the first 30 seconds and then hold 20 r/s for the next 30 seconds, right? And after that the load will drop to 0 and start to ramp up to 20r/s again?

Generally in my tests I'd like to ramp up to a certain rate in warmup and then hold the load, i.e. to have separate load configuration for warmup phase. But looks like it's not possible to configure it that way?

Thank you.

**Comment by AntyaDev** [comment]
Hi @andreycha 

> What kind of load will be produced during warmup phase? I assume it will ramp up to 20r/s within the first 30 seconds and then hold 20 r/s for the next 30 seconds, right? And after that the load will drop to 0 and start to ramp up to 20r/s again?

Yes, that's right.

You highlighted a very good point regarding supporting the custom warm-up workload. For now, NBomber doesn't provide such a thing, and it's easy to add.

**Comment by AntyaDev** [comment]
@andreycha I added a task for this #655 
Is it critical for you?

**Comment by andreycha** [comment]
@AntyaDev thanks for clarifying it! Not that it makes NBomber not usable, just makes some tests less "clean" from configuration and load perspective. But would be definitely nice to have more fine-grained configuration especially if it's easy to support.
