### ISSUE TITLE
Clean runs before the last step of scenario finished

### ISSUE THREAD

**Issue by destructorvad** [VIP-Logic/NBomber#656]
Nbomber version - 5.4.1

At the moment I have long scenario, but run it with the following settings (and 3 steps):
```
{
  "ScenarioName": "Create_relations_between_1_and_200_assets",
  "WarmUpDuration": "00:00:10",
  "LoadSimulationsSettings": [
    { "Inject": [ 1, "00:00:01", "00:00:05" ] }
  ],
  "MaxFailCount": 5
},
```
But the total scenario duration is near 2 min - since it waits last step to be finished.
But debugging session showed me following sequence of actions:

1. Clean (method passed to WithClean) started
2. after some iterations of last step is called (it has a foreach cycle) - throws error - since some resources are cleaned up
3. Clean finished

**Comment by AntyaDev** [comment]
Hi @destructorvad 
By default NBomber waits 1 min to finish all running scenarios/steps. 

I suggest you to consider incresing [scenario completion timeout](https://nbomber.com/docs/nbomber/timeouts#scenario-completion-timeout)

Also, in the next release we will add CancellationToken for such cases: https://github.com/PragmaticFlow/NBomber/issues/645
