### ISSUE TITLE
Step names are duplicated in Charts tab of HTML report

### ISSUE THREAD

**Issue by andreycha** [VIP-Logic/NBomber#664]
NBomber version: 5.5.0

I have a scenario with two steps. When I open HTML report, I see correct step names in all the tables:
![image](https://github.com/PragmaticFlow/NBomber/assets/1696046/6e87d3c6-aaad-4333-be80-0c61aa8bc203)

However, in Charts tab names are duplicated:
![image](https://github.com/PragmaticFlow/NBomber/assets/1696046/30123810-9ce5-43b5-b7ab-8be2ea67d2cb)

CSV and text reports look correct.

**Comment by AntyaDev** [comment]
Hi @andreycha 
Thanks for your report.
I think it's connected to this issue: https://github.com/PragmaticFlow/NBomber/issues/647
If yes, we plan to deliver the fix for v5.6

**Comment by AntyaDev** [comment]
Btw do you know how to reproduce it?
Can I get some examples to reproduce it? Or maybe you can describe your load test configuration that I can try to simulate.

**Comment by andreycha** [comment]
Hi @AntyaDev , yep, looks very similar. Please feel free to close this issue as duplicate if needed,

**Comment by andreycha** [comment]
My scenario setup looks like this:

```cs
var scenario = Scenario.Create("SearchAndOpen_RequestsPerMinute", async ctx =>
    {
        var listResponse = await Step.Run("GetPendingApprovals", ctx, async () =>
        {
            // HTTP API call, around 500ms
        });

        if (listResponse.IsError)
        {
            return Response.Fail(listResponse);
        }

        await Task.Delay(TimeSpan.FromMilliseconds(300)); // delay to simulate real user

        var detailsResponse = await Step.Run("GetPendingApprovalDetails", ctx, async () =>
        {
            // HTTP API call, around 500ms
        });

        return detailsResponse.IsError ? Response.Fail(detailsResponse) : Response.Ok(detailsResponse);
    });
```

Load simulation (if it matters; and I know that ramp up with 1RPS doesn't make much sense :)):

```json
"LoadSimulationsSettings": [
  { "RampingInject": [ 1, "00:00:01", "00:01:00" ] },
  { "Inject": [ 1, "00:00:01", "00:01:00" ] }
]
```

I'll try to reproduce the issue with a similar sample and provide the full solution (tests are executed as xUnit tests).
