### ISSUE TITLE
Show Standard Deviation in HTML Report

### ISSUE THREAD

**Issue by botondberes** [VIP-Logic/NBomber#676]
Hi Anton,

we just noticed that the generated Report doesn't show the StdDev values even though they are present in the reports ViewModel.
So we can get them out of the report by checking the page source but we would love to have it shown just like the Max, Min and Mean, etc. values.

P.S.: Median would be great to have too.

Thanks in advance!

**Comment by AntyaDev** [comment]
Hi @botondberes 
That sounds reasonable. 
I will add this to our backlog.

**Comment by AntyaDev** [comment]
Hi @botondberes 
Please try NBomber 5.7.0-beta.3
