### ISSUE TITLE
Problem with license validation

### ISSUE THREAD

**Issue by BaterPL** [VIP-Logic/NBomber#679]
Some time ago, we ordered an NBomber license and we’re experiencing quite flaky behavior. Sometimes it works, but other times we receive an error stating: "NBomber License is not found on license server. Probably your license key is expired.". However, after some time, it works again.
 
What might be the reason for such behavior? Is there any external verification of the license performed on test startup, or is the license key self-contained?

**Comment by AntyaDev** [comment]
Hi @BaterPL 
Do you observe issues with license validation for some specific environment? Or does it happen on any (local, staging) environments?

Also how many developers use NBomber in your company?

**Comment by BaterPL** [comment]
Currently we're experimenting with the tool, so I observed that in my local environment. For the same reason it's not actively used by more than 1-2 users at the same time.

**Comment by AntyaDev** [comment]
> What might be the reason for such behavior? 

The tool checks the license on each run. You should have a stable internet connection.
Btw, what the ratio of such failures to normal runs? 

I think we can run a tool with enabled tracing to see why the license check request is falling.

**Comment by BaterPL** [comment]
Okay, so it's most likely a proxy on our side. Could you provide the addresses that are called for license validation so we can whitelist them?

Additionally, what concerns me is that in our target configuration, servers executing perf test won't have internet access. Is there any possibility of making it work in that configuration?

**Comment by AntyaDev** [comment]
Hi, I have sent a list to your email.

> Is there any possibility of making it work in that configuration?

If there is no other way I think we could add such option.

**Comment by BaterPL** [comment]
Thanks, and for me that option would be highly desired :)

**Comment by BaterPL** [comment]
Hi @AntyaDev, 
I've just tried the latest version and I'm still facing the same problem - internet connection is required to validate license. This is the error I'm getting: 
`[ERR] NBomber License server communication error: 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (license.nbomber.com:443)'.`
As mentioned earlier, our perf test servers are not connected to the internet, so how can I switch to offline license validation?

**Comment by AntyaDev** [comment]
Hi @BaterPL ,
NBomber doesn't support offline validation. We made some improvements regarding the retry policy, logs, etc, and removed redirects from the auth flow. However, NBomber is still required to use the internet for authorization. Would it be possible to whitelist **license.nbomber.com** ?

**Comment by BaterPL** [comment]
Unfortunately, it's not possible because the internet connection is blocked on the test network, and we can't wave that restriction.

**Comment by AntyaDev** [comment]
@BaterPL, can you please send me your email on nbomber@nbomber.com ?
I will invite you to our Slack channel.

**Comment by AntyaDev** [comment]
Hi @BaterPL 
Just in case, we added an offline license validation.
https://nbomber.com/docs/getting-started/license#offline-license-validation
