### ISSUE TITLE
Help: Why is only one copy running even if I specified multiple copies?

### ISSUE THREAD

**Issue by CDboyOne** [VIP-Logic/NBomber#680]
I created a console project and tested NBomber:
```
using NBomber.CSharp;
using NBomber.Contracts;

Console.WriteLine("Hello, World!");

var scenario = Scenario.Create("MultiThread", scenectx =>
{
    int threadIndex = scenectx.ScenarioInfo.InstanceNumber;
    int callIndex = (int)scenectx.InvocationNumber - 1;

    scenectx.Logger.Warning($"THREAD INDEX {threadIndex} CALL INDEX {callIndex}");
    
    return Task.FromResult(Response.Ok() as IResponse);
})
.WithLoadSimulations(
    Simulation.IterationsForConstant(copies: 4, iterations: 4)
)
.WithoutWarmUp();

NBomberRunner.RegisterScenarios(scenario).Run();
```
I print the ```InstanceNumber``` and ```InvocationNumber``` of every invocation. I want to see 4 different ```InstanceNumber``` but the log is:

> 2024-04-12 22:22:16.671 +08:00 [WRN] [ThreadId:7] THREAD INDEX 1 CALL INDEX 0
> 2024-04-12 22:22:16.673 +08:00 [WRN] [ThreadId:7] THREAD INDEX 1 CALL INDEX 1
> 2024-04-12 22:22:16.673 +08:00 [WRN] [ThreadId:7] THREAD INDEX 1 CALL INDEX 2
> 2024-04-12 22:22:16.673 +08:00 [WRN] [ThreadId:7] THREAD INDEX 1 CALL INDEX 3

Could anybody tell me the reason, and how can I get my expected result?

The repository link is [here](https://github.com/CDboyOne/NBomberTest).

**Comment by AntyaDev** [comment]
```csharp
var scenario = Scenario.Create("MultiThread", async scenectx =>
        {
            var callIndex = scenectx.InvocationNumber;

            scenectx.Logger.Warning($"INSTANCE NUMBER {callIndex}");

            return Response.Ok();
        })
        .WithoutWarmUp()
        .WithLoadSimulations(
            Simulation.IterationsForConstant(copies: 4, iterations: 4)
        );
```

**Comment by CDboyOne** [comment]
> ```cs
> var scenario = Scenario.Create("MultiThread", async scenectx =>
>         {
>             var callIndex = scenectx.InvocationNumber;
> 
>             scenectx.Logger.Warning($"INSTANCE NUMBER {callIndex}");
> 
>             return Response.Ok();
>         })
>         .WithoutWarmUp()
>         .WithLoadSimulations(
>             Simulation.IterationsForConstant(copies: 4, iterations: 4)
>         );
> ```

Thanks for your response. I ran your code and got the following log:
> 2024-04-12 23:06:37.263 +08:00 [WRN] [ThreadId:7] INSTANCE NUMBER 1
> 2024-04-12 23:06:37.265 +08:00 [WRN] [ThreadId:7] INSTANCE NUMBER 2
> 2024-04-12 23:06:37.265 +08:00 [WRN] [ThreadId:7] INSTANCE NUMBER 3
> 2024-04-12 23:06:37.265 +08:00 [WRN] [ThreadId:7] INSTANCE NUMBER 4

The ThreadId is same (7), but what I want is 4 different ThreadId. How can I get copies running on different threads?

**Comment by AntyaDev** [comment]
It's because of the scheduling. NBomber is using TPL (Task library) for multithreading. Please try to introduce some await like task.Delay() inside your scenario. And also run more iterations.

**Comment by AntyaDev** [comment]
Since your load test does nothing the scheduler is quite smart to optimise it. Try to introduce some pause or send HTTP request for example.

**Comment by CDboyOne** [comment]
> Since your load test does nothing the scheduler is quite smart to optimise it. Try to introduce some pause or send HTTP request for example.

Thanks! I used the following code to print the invocation count of each instance:
```
using NBomber.CSharp;

int NCOPY = 4;
int[] counts = new int[NCOPY];
counts.AsSpan().Fill(0);

var scenario = Scenario.Create("MultiThread", async scenectx =>
{
    int threadIndex = scenectx.ScenarioInfo.InstanceNumber;
    lock (counts)
    {
        counts[threadIndex]++;
    }

    await Task.Delay(5);
    
    return Response.Ok();
})
.WithoutWarmUp()
.WithLoadSimulations(
    Simulation.IterationsForConstant(copies: 4, iterations: 100)
);

NBomberRunner.RegisterScenarios(scenario).Run();

for (int i = 0; i < counts.Length; i++)
    Console.WriteLine($"Instance {i} called {counts[i]} times.");
```

When I use ```await Task.Delay(5);``` I got:
> Instance 0 called 3 times.
> Instance 1 called 51 times.
> Instance 2 called 0 times.
> Instance 3 called 46 times.

When I use ```await Task.Delay(500);``` I got:
> Instance 0 called 25 times.
> Instance 1 called 26 times.
> Instance 2 called 24 times.
> Instance 3 called 25 times.

I want to mock the situation that 4 threads are calling my method at the same time, so I need to get invocations distributed on each scenario instance equally. But it seems impossible when my method is fast. How can I reach my purpose?

**Comment by AntyaDev** [comment]
For benchmarking, I suggest you to look at https://benchmarkdotnet.org/

**Comment by CDboyOne** [comment]
> For benchmarking, I suggest you to look at https://benchmarkdotnet.org/

Actually I need to do load test with a set of different test cases, and measure the average time and other statistics on the set. But BenchmarkDotNet will do benchmarking on each case separately, which cannot satisfy my need.

**Comment by AntyaDev** [comment]
btw you dont need lock here, NBomber will run each scenario on dedicated Task/Thread

```
lock (counts)
{
    counts[threadIndex]++;
}
```

**Comment by AntyaDev** [comment]
Try to use [Iterations for Inject](https://nbomber.com/docs/nbomber/load-simulation#iterations-for-inject).

**Comment by AntyaDev** [comment]
Ah sorry, I am wrong about your usage of `lock`. You need to use it.
If you work with primitive number I suggest you consider [Interlocked.Increment](https://learn.microsoft.com/en-us/dotnet/api/system.threading.interlocked.increment?view=net-8.0)

**Comment by CDboyOne** [comment]
@AntyaDev Thank you for your advice. I am trying KeepConstant simulation now. This seems to be a good choice.
