### ISSUE TITLE
Reporting maxes out at about 12 minutes

### ISSUE THREAD

**Issue by ctissellb** [VIP-Logic/NBomber#683]
We regularly run longish tests and have noticed the the NBomber summary report consistently truncates the report to about 12 minutes.  This applies to both the text and HTML reports.

For example a recent report shows this summary:

test info
test suite: Standard Load Tests
test name: All Scenarios
session id: 2024-04-26_18.16.78_session_ac840d43

scenario: Player Sim
  - ok count: 9974
  - fail count: 9640
  - all data: 0 MB
  - duration: 00:12:10

load simulations: 
  - ramping_constant, copies: 20000, during: 00:20:00
  - keep_constant, copies: 20000, during: 00:10:00
  
  
  
 Yet the full log clearly shows the test ran longer than 12 minutes:
  
2024-04-26 11:16:33.022 -07:00 [INF] [ThreadId:33]  Sending new Fake sign on request
. . . 
2024-04-26 11:45:21.421 -07:00 [INF] [ThreadId:2518]  Sending zombie DS heartbeat:

**Comment by AntyaDev** [comment]
Hi @ctissellb 
Is this behavior applicable to any load tests with a duration greater than 12 minutes?

**Comment by ctissellb** [comment]
Yes the test in the original post was actually over 30 minutes, but the summary and graphs only shows 12 minutes worth of data.

**Comment by AntyaDev** [comment]
Thanks

**Comment by AntyaDev** [comment]
Hi @ctissellb ,

We have tried many times to reproduce the issue but unfortunatelly no luck.
I have attache the HTML report with 22 min duration.
Could you please provide the code example that reprduce this issue?

[nbomber_report_2024-06-02--19-37-12.zip](https://github.com/user-attachments/files/15527008/nbomber_report_2024-06-02--19-37-12.zip)

**Comment by ctissellb** [comment]
I should be able to put something together in the next week or two.

**Comment by AntyaDev** [comment]
Hi @ctissellb 
Are there any updates on this issue?

**Comment by AntyaDev** [comment]
Hi @ctissellb 
Are there any updates on this issue?

**Comment by AntyaDev** [comment]
Hi @ctissellb 
Any updates?

**Comment by ctissellb** [comment]
Morning. Apologies I've been on extended leave.

I'm having trouble reproing the issue. I need to run some longer to tests to see if it manifests again. Feel free to close or backlog this item and I can re-open it if necessary.
