### ISSUE TITLE
Provide list of license servers

### ISSUE THREAD

**Issue by lunns0** [VIP-Logic/NBomber#684]
Hi, we are using NBomber in a restricted environment and must whitelist any outbound internet traffic. As a result we will not be able to access the NBomber licensing servers without first whitelisting them.

Are you able to please either publish these servers, or email them to me? 

Thanks,
Steve.

**Comment by AntyaDev** [comment]
Hi @lunns0 
Please whitelist:
- https://nbomber.com/
- https://antyadev-license-server-7g2jn.ondigitalocean.app/
