### ISSUE TITLE
Client Pool - clean client before it can be reused

### ISSUE THREAD

**Issue by RomanPoprava** [VIP-Logic/NBomber#693]
Question - if the thread has ended and the client is free to be taken by another thread - is there any mechanism to clear team data (header, cookies, etc) of that specific client within client pool?
What I saw in the documentation - there is only `DisposeClients()` can be called, usually in 'WithClean()', but this method has called only once after bombing phase and it's disposing all clients in the client pool. What we need is to clean client data when thread has ended, so the client may be reused by another thread within one scenario.

**Comment by AntyaDev** [comment]
Not sure I understand. Can you please elaborate on your use case? And what prevents you from cleaning all necessary data at the end of the thread?
