### ISSUE TITLE
Make it possible to remove Net real-time stats table from Console

### ISSUE THREAD

**Issue by iskvortsov** [VIP-Logic/NBomber#705]
Floating Net metrics table obscures some of the logs that are required for debugging (see the screenshot)

Would be cool to have some run parameter to remove it entirely or make it display only the final metrics after test run.

<img width="1586" alt="Screenshot 2024-07-03 at 13 26 30" src="https://github.com/PragmaticFlow/NBomber/assets/17781596/a6090d10-05c9-40ce-9fbc-1e4ae8712e0a">

**Comment by AntyaDev** [comment]
Hi @iskvortsov ,

Please try the latest beta [5.8.0](https://www.nuget.org/packages/NBomber/5.8.0-beta.0)

we added CLI args:
```
--display-console-metrics=false
```

also C# API:
```csharp
NBomberRunner
    .RegisterScenarios(scenario)
    .DisplayConsoleMetrics(false)
```

also JSON Config
```json
{
  "GlobalSettings": {        
    "DisplayConsoleMetrics": false
  }
}
```

**Comment by iskvortsov** [comment]
@AntyaDev thank you! It will be a huge time saver for me. Works great, too!
