### ISSUE TITLE
Request: Add simple way to set failure and latency thresholds in the config.json

### ISSUE THREAD

**Issue by ctissellb** [VIP-Logic/NBomber#707]
It would be quite handy to be able to use the config to set global or per scenario latency and failure percent thresholds rather than MaxFailCount.

For instance:

MaxFailPercent: 10 <-- Scenario failure rate must not exceed 10%
MaxHighLatencyPercent: [10, 500] <-- The number of scenarios that take longer than 500ms to complete must not exceed 10%

**Comment by AntyaDev** [comment]
This is actually a very good suggestion.
I will add it to the next release v5.8.0

**Comment by AntyaDev** [comment]
Hi @ctissellb 
What do you think about this API:
```json
"GlobalSettings": {

        "ScenariosSettings": [
            {
                "ScenarioName": "scenario",
                
                "ThresholdSettings": [
                    { "StepName":  "global-info", "StatusCode": ["200", "Count => 20"] },
                    
                    { "StepName":  "login", "Errors": "Percent > 20" },
                    
                    { "StepName":  "logout", "Latency": "P50 >= 30" },
                    
                    { "StepName":  "logout", "Latency": "Max >= 900" },
                    
                    { "StepName":  "logout", "Request": "RPS >= 900" }                    
                ]
            }
        ]
}
```
- It should support GlobalSettings
- It should be displayed on HTML report
- It should support "StartMeasure from specific time"
- It should support AbortScenario after failure count

**Comment by ctissellb** [comment]
Works for me!

**Comment by AntyaDev** [comment]
Hey @ctissellb 
Could you please try the latest beta: https://www.nuget.org/packages/NBomber/5.8.0-beta.3
[Here](https://github.com/PragmaticFlow/NBomber/issues/746) you can find more info about Threshold feature

**Comment by AntyaDev** [comment]
https://www.nuget.org/packages/NBomber/5.8.0-beta.5
