### ISSUE TITLE
How to get/see the exception details such as StackTrace?

### ISSUE THREAD

**Issue by Sina-Soltani** [VIP-Logic/NBomber#716]
Hi,

Is there any way to get/see the details of the exceptions that have happened during the test?
Right now, we start the NBomber to run the tests. After the tests are finished a report is generated that can be seen in the console.
The report says which scenarios were OK and which were failed.
In the Failed table, it only shows the message of an exception that probably happened during the tests.
But we would like to know where exactly it happened.
Is there any way to access/see the StackTrace of the exception? Otherwise we can't find the exact place of the failure.

Thanks.

**Comment by AntyaDev** [comment]
Hi @Sina-Soltani ,
Did you check the logs folder?

There should be a log.txt file where you can find details of the exceptions.

Does it make sense?

**Comment by Sina-Soltani** [comment]
Hi, yes. I found the details in the log.txt file.

Thanks.
