### ISSUE TITLE
Concurrent problem with Dictionaries in HttpClient.Headers

### ISSUE THREAD

**Issue by Sina-Soltani** [VIP-Logic/NBomber#718]
Hi,

I'm trying to use an HttpClient in my test scenarios.

The HttpClient is unique for each Scenario. It's created inside the Scenario.
Some Http Headers need to be added to the HttpClient before sending the requests to the BackEnd API.

The problem is, we get the following exception after the NBomber is finished:
```
System.ArgumentException: An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
```

I think it's happening because of concurrent access to the Headers of the HttpClient which is a dictionary.
So, multiple threads try to add a Header at the same time because NBomber Scenarios are trying to send 50 requests per seconds.

Is there any solution for this?

**Comment by AntyaDev** [comment]
Hi @Sina-Soltani ,
Can you please post an example here? 
Also, please read this documentation: 
https://nbomber.com/docs/protocols/http#httpclient

**Comment by AntyaDev** [comment]
I assume you should use a single instance of HttpClient between Scenario copies (instances). 
In each Scenario copy (instance), you should create a HttpRequestMessage and send it to a single HttpClient.

**Comment by Sina-Soltani** [comment]
You are right. However, I can't do that, because this HttpClient is actually inside a DLL file (nuget).

Let's say, someone has created a Client API nuget package for his BackEnd API so that the clients (us) can work with the BackEnd API with strongly-typed data.

He has created this Client API package using `NSwag Studio`. It gets a `swagger.json` and generates the corresponding classes, interfaces, objects and so on.

So, when I'm using it, I don't work directly with the HttpClient.
It's something like this:
```c#
var product = await clientApi.GetProduct("124123-fqwf-212313-213");
```

The package owner adds some Headers before sending the request.

**Comment by Sina-Soltani** [comment]
I also want to mention that the all tests are using a WebApplicationFactory<T> from `Microsoft.AspNetCore.Mvc.Testing`.

So, the Console Program creates a Host using the `WebApplicationFactory<T>` for testing.

Then we use the `WebApplicationFactory.CreateClient()` method inside each scenario to create an HttpClient.

We then give this HttpClient to the ClientApi package because it needs it inside its constructor.

**Comment by AntyaDev** [comment]
> System.ArgumentException: An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderD

Can you please check that you don't add duplicated keys? You can use Dictionary to filter duplicates and then add them to HTTP Client

**Comment by Sina-Soltani** [comment]
I fixed it by creating an instance of the client (which has an HttpClient inside) in each step in each scenario.
It's working fine now.
Thanks.

**Comment by AntyaDev** [comment]
@Sina-Soltani If you need any help, just ask us)

You need to check if you don't face issues with sockets: https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
The alternative would be to consider using [ClientPool](https://nbomber.com/docs/nbomber/client-pool), which will allow you to create a list of clients and then reuse them.
