### ISSUE TITLE
Correct NuGet Packages to Debug NBomber Tests?  (Visual Studio (Repeated System.IO.IOException , Console.dll)

### ISSUE THREAD

**Issue by charlesdwmorrison** [VIP-Logic/NBomber#729]
What are the correct NuGet packages needed to debug NBomber tests?
Following the post at https://nbomber.com/blog/2021/04/14/nbomber-2-0/ , and also after looking at the exceptions in the VS debug output, I have the following NuGet packages installed (I am exeucting a Playwright test per the example here: https://nbomber.com/docs/protocols/webbrowser/).

**Here are my Visual Studio 2022 NuGet Packages**
NBomber  5.7.0
NBomber.WebBrowser 0.1.0
NUnit 4.2.2
NUnit2 TestAdapter 4.6.0
PuppeteerSharp 19.0.2
FsToolkit.ErrorHandling
FsToolkit.ErrorHandling.TaskResult ver. 4.6.0
Microsoft.NET.Test.Sdk  8.0.9
Microsoft.Playwright 1.46.0
Microsoft.Playwright.TestAdater 1.46.0
Serilog.AspNetCore 8.0.2
Serilog.Sinks.Spectre 0.5.0
Serilog.Sinks.SpectreConsole 0.3.3
Spectre.Console.Extensions.Progress 1.0.0
Spectre.Console.Extensions.Table 1.0.0

Despite have the above packages installed, my VS debug output, always (on every run)  shows exceptions, which always occur for me when I execute any NBomber scenario in Visual Studio 2022, latest version.

- I am on .Net 8.0. 
- I There is also a definite  ~45 second delay at the start of every test (debug or normal run). My guess is that these exceptions are a big part of the delay.
- In my current test, I have 16 of them at the start of a test.
- I am including a few other errors at the start.

**Here is an example output** (15 System.IO.IOExceptions) 
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\Serilog.Settings.Configuration.dll'. Symbols loaded.
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\Microsoft.Extensions.DependencyModel.dll'. Symbols loaded.
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\Serilog.Sinks.File.dll'. Symbols loaded.
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\Serilog.Enrichers.Thread.dll'. 
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\Serilog.Sinks.SpectreConsole.dll'. Symbols loaded.
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\Spectre.Console.dll'. 
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\FsToolkit.ErrorHandling.TaskResult.dll'. 
Exception thrown: 'System.IO.DirectoryNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\System.Reactive.dll'. 
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\HdrHistogram.dll'. 
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.MissingMethodException' in Serilog.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll

What am I doing wrong? How can I get rid of these exceptions and speed up my test?
Note that my test runs both in normal and debug mode, there is just this very slow start. 
Am I supposed to be seeing, btw, seeing a Spectre console during the run of my test? As showing here: https://nbomber.com/blog/2021/04/14/nbomber-2-0/?
How in an NUnit test id this console supposed to open?

Thanks.

**Comment by charlesdwmorrison** [comment]
Update, I removed all the Spectre.Console packages from the above because I noticed that with those installed, I was not getting the report from a test output. 

With the Spectre.Console packages removed, I still get the 45 second delay in the test start, but instead of "System.MissingMethodException", I get about the same number of "System.IO.IOException" exceptions. E.g., 

'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\Serilog.Sinks.SpectreConsole.dll'. Symbols loaded.
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\Spectre.Console.dll'. 
Exception thrown: 'System.IO.IOException' in System.Console.dll
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\FsToolkit.ErrorHandling.TaskResult.dll'. 
Exception thrown: 'System.IO.DirectoryNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\System.Reactive.dll'. 
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\source\repos\EnsentaNBomberTests\NBomber\bin\Debug\net8.0\HdrHistogram.dll'. 
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll

How do I avoid this 45 second delay in the start of every test, which I think is due to these exceptions?

**Comment by AntyaDev** [comment]
Hi @charlesdwmorrison 
Have you tried to run Demo examples?
https://github.com/PragmaticFlow/NBomber/tree/dev/examples/Demo

Just to check that they are working for you

**Comment by charlesdwmorrison** [comment]
I will try these and see what happens. Thanks.

**Comment by charlesdwmorrison** [comment]
Yes, I am afraid I get the delay and the System.console exceptions quite a bit or worse than with my samples.
I do see that these samples contain the recommended packages, which is a help.
But running the xUnit SimpleHttpExample, I get 45 second plus delay, and the  the following exceptions are shown when I run in Debug mode.
I have been thinking, this COULD be due to security software my company has installed: we have both SecureDoc Full Disk Encryption as well as Netskope.
Both of these definitely slow up the start and development of the old Visual Studio load test harness, but not quite as much as I see here in NBomber. (I don't see any Console exceptions when I debug in the Visual Studio load tool.
I think that NBomber is a fantastic tool . It IS the load tool I have been waiting for, and the 45 second start up won't stop me from using it.
I was just wondering if I still might be missing a package. 
To the Demo packages, I didn't change anything.



**Partial Debug Output when Running SimpleHttpExample.**
testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Xml.XPath.XDocument.dll'. Symbols loaded.
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\Documents\Downloads\NBomber-dev\NBomber-dev\examples\xUnitExample\bin\Debug\net8.0\xunit.runner.reporters.netcoreapp10.dll'. 
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Users\CMorrison\Documents\Downloads\NBomber-dev\NBomber-dev\examples\xUnitExample\bin\Debug\net8.0\xunit.runner.visualstudio.dotnetcore.testadapter.dll'. 
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.DirectoryNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. 
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\Microsoft.IntelliTrace.TelemetryObserver.Common.dll'. 
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\Microsoft.IntelliTrace.TelemetryObserver.CoreClr.dll'. 
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'System.IO.IOException' in System.Console.dll
Exception thrown: 'Xunit.Sdk.TrueException' in xunit.assert.dll
An exception of type 'Xunit.Sdk.TrueException' occurred in xunit.assert.dll and wasn't handled before a managed/native boundary
Assert.True() Failure

The thread '.NET TP Worker' (22348) has exited with code 0 (0x0).
The thread '.NET TP Worker' (20668) has exited with code 0 (0x0).
The thread '.NET TP Worker' (20920) has exited with code 0 (0x0).
The thread '.NET TP Worker' (22640) has exited with code 0 (0x0).
The thread '.NET TP Worker' (3536) has exited with code 0 (0x0).
The thread '.NET TP Worker' (21288) has exited with code 0 (0x0).
The thread '.NET TP Worker' (19492) has exited with code 0 (0x0).
The thread '.NET TP Worker' (19640) has exited with code 0 (0x0).
The thread '.NET TP Worker' (20540) has exited with code 0 (0x0).
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
The thread '.NET Long Running Task' (18020) has exited with code 0 (0x0).
The thread '.NET Long Running Task' (15128) has exited with code 0 (0x0).

**Comment by AntyaDev** [comment]
This was the first time I had seen such behavior. 
What happens if you run Hello World as a Console Application (not Nunit/xUnit test)?
Also, do you see any difference when you compile with Release settings?

**Comment by charlesdwmorrison** [comment]
When I recall a similar, but not as long delay with the Visual Studio load tool, and also with other write operations on my office computer, which I am 90% sure are due to SecureDoc, I am not that surprised by a delay here. I have complained numerous times to my operations teams.
So what could be going on here with NBomber is a timing issue in NBomber as it tries to write to (Spectre?)  console , but the console on my computer is too slow because of SecureDoc Full Disk Encryption (which I can't turn off).  
  I will play around this morning running Hello World as a Console and report back here.
  But I was just wondering two things:
1. Would I be better off running NBomber tests in Visual Studio Code and not Visual Studio 2022? I notice from this and other videos that if I run in VS Code, there is a separate pop up (with a progress bar): https://www.youtube.com/watch?v=3O3c2KKMxiM (~ min 7:30). So maybe I should give VS Code a try too? Maybe that is the console VS is looking for in the above exceptions?
2. Is there some way to get that popup in normal Visual Studio 2022? I kept Googling for some command to force Visual Studio to open a command window during a Unit test, but I don't see a way to do that. I just get a the chart shown in the above video at the end of the test, at the bottom of VS Test Explorer, not in real-time, only at the end of the test  and not in color as shown in the above video. 
BTW, I don't think it's a breach of security to attach a screenshot of some of the nasty processes that happen just during a VS startup. You can see here on start up some of the disk usage that occurs.
ExecutionPrevention is sort of a new one, but LsiAgent and Minion host will create ~a constant 15% disk utilization on my Dell Laptop with an SSD during any Visual Studio load test. This disk security is on all corporate computers.

![image](https://github.com/user-attachments/assets/84df65f8-3358-4586-8313-0226a1be992c)

Here is another shot taken at approximately the time I see the System.console exceptions:
![image](https://github.com/user-attachments/assets/2080a76a-201b-4a7e-8984-e9d572f4a89a)

**Comment by AntyaDev** [comment]
> there is a separate pop up (with a progress bar)

I think that the progress bar is an indicator of warmup. https://nbomber.com/docs/nbomber/scenario#scenario-warmup
By default (if you don't specify) warm-up duration is 30 sec

By the way, I remember that there should be some way to instruct antivirus tools not to scan a specific folder or exe file. You could discuss this with your security guys.

I also recommend trying NBomber on a laptop without antivirus to see the difference and to get confidence that this slowdown is affected by antivirus and not by some misconfiguration.

**Comment by charlesdwmorrison** [comment]
Your above suggestions make great sense. It could be anti virus in addition to the NetScope and SecureDisk.
I should have tried running your Console Demo before. Much smoother experience! 
When I run the Console Demo, I DO NOT get any of the exceptions mentioned in my above post. A windows console pops up and no exceptions:

![image](https://github.com/user-attachments/assets/53edebf2-f43c-4b66-aef7-d7bc6d62e9eb)

I think my next steps are to talk to my system administrators, but also I keep thinking that I should try NBomber in VS Code. I perhaps might get a better experience there.
I also can move my solution to a machine without AV as you suggested. 
I will work on this and post any findings here.
BTW, we purchased a license for NBomber this past week. Very excited!

**Comment by AntyaDev** [comment]
Hi @charlesdwmorrison 
Great news!
If you need any help, you can use this [chat](https://github.com/PragmaticFlow/NBomber/discussions/new/choose)
Or you can send us your email, and we add you to the Slack channel.

**Comment by CMorrisonJHA** [comment]
I have sent an email about this to the author. After much experimentation, I do not believe this is due to Antivirus or SecureDisk or Netskope. 
I will hopefully post a solution here when we find it.

**Comment by AntyaDev** [comment]
Hi @CMorrisonJHA 
Thanks for your deep analysis. I can say that we usually run NBomber tests on xUnit, NUnit, Console application.
In the latest beta version, NBomber allows to disable the console output (it will be documented when we release version 5.8)
```csharp
NBomberRunner.DisplayConsoleMetrics(false)
```

I will mark this issue as a bug, and we will try to see what can be improved.

**Comment by CMorrisonJHA** [comment]
Good to know you are already on top of this. I think fixing it will increase the adoption of an already great tool. Making a great tool greater!
I just want to point out that with NBomber5.8.0-beta.1 I am still seeing the error, even when I put in the .DisplayConsoleMetrics(false) .
I have also tried DisplayConsoleMetrics(true)  -- same result. (see screenshot 02 below).


  var result = NBomberRunner
      .RegisterScenarios(scenario)
      .DisplayConsoleMetrics(false)
      .Run();

**Comment by AntyaDev** [comment]
Thanks @CMorrisonJHA 
We will do some research to find a workaround. It's great to hear that you like NBomver!

**Comment by CMorrisonJHA** [comment]
Just want to say I see this fixed ahead of time in build 5.8.1. Great job!

**Comment by AntyaDev** [comment]
Thank you, @CMorrisonJHA, for the information!
I then will close this task for now.
