### ISSUE TITLE
Http Request removes Header "Content-Type"

### ISSUE THREAD

**Issue by jethrob** [VIP-Logic/NBomber#731]
When using the example from "examples/Demo/HTTP/SimpleHttpExample.cs" I noticed that the header "Content-Type" is missing.

The same happens with Json requests as well.

Output from Trace below.

2024-09-06 16:28:39.475 +02:00 [DBG] [ThreadId:10] HTTP Request:
 TraceId: 51f828d0451e4d33846bb19a4284a8cf
 Method: GET
 RequestUri: "https://nbomber.com/"
 HttpVersion: 1.1
 Headers: 
 Content:

**Comment by AntyaDev** [comment]
Did you find some fix?
