### ISSUE TITLE
Unable to find method 'NBomberRunner. WithScenarioCompletionTimeout' in version 5.7.0

### ISSUE THREAD

**Issue by Libra321** [VIP-Logic/NBomber#739]
I downloaded the source code of v5.7.0, but when calling it, I couldn't find the method "NBomberRunner. WithScenarioCompletionTimeout". I couldn't find this method in the source code either. Is the code not up-to-date? It's possible in your demo because it references the Nuget package

**Comment by AntyaDev** [comment]
NBomber v5 is distributed under a proprietary license. Please check our license text.
